#####
## Sample configuration file for Microsoft Windows.
## This is YAML, so structure and indentation is important.
## Lines can be uncommented by removing the #. You should not need to change the number of spaces after that.
## Config options have a single #, comments have a ##. Only uncomment the single # lines if you need them.
#####

## Uncomment dataDirectory if you need to manually set the directory.
## Note: Not used with Data Ingest / Fleet Management configuration
#dataDirectory: C:\ProgramData\LogScale Collector
 
sources:
  ## Collect windows event logs
  windows_events:
    type: wineventlog
    channels:
      - name: Application
      - name: Security
      - name: System
      - name: Windows PowerShell
      - name: ForwardedEvents
    sink: next-gen-siem-windows

  ## Collect syslog udp 1514.
  syslog_udp_1514:
    type: syslog
    mode: udp
    port: 1514
    ## Optional: Max allowed event size (default = 2048 bytes), messages larger than this will be truncated
    ## Increase this value if you expect larger syslog messages. 
    ## Be cautious when increasing this value, as it affects memory usage and network bandwidth.
    ## The max value is 950000 bytes.
    maxEventSize: 2048
    sink: next-gen-siem-syslog-udp

## Each sink will have a unique token and url that correspond to Data Connector you wish to send data to.     
sinks:

  ## This sink receives data from "windows_events" source above   
  next-gen-siem-windows:
    type: hec
    ## Replace with your specified ingest token.
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ## Replace with the "Ingest URL" on the FLC download page. It must include the "https://" at the beginning.
    ## NOTE: you MUST REMOVE the "services/collector" from the URL if it exists.  
    url: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.ingest.YY-Y.crowdstrike.com
    ## Optional: maxBatchsize generally handled automatically by FLC but can be manually set if needed
    ## If set, as of Aug 2025, max payload before compression limit is 32M, minus 2M to account for meta-data (plus 2M buffer)
    #maxBatchSize: 28000000
    workers: 4
  
  ## This sink receives data from "syslog_udp_1514" source above  
  next-gen-siem-syslog-udp:
    type: hec
    ## Replace with your specified ingest token.
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    ## Replace with the "Ingest URL" on the FLC download page. It must include the "https://" at the beginning.
    ## NOTE: you MUST REMOVE the "services/collector" from the URL if it exists.  
    url: https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.ingest.YY-Y.crowdstrike.com
    ## Optional: maxBatchsize generally handled automatically by FLC but can be manually set if needed
    ## If set, as of Aug 2025, max payload before compression limit is 32M, minus 2M to account for meta-data (plus 2M buffer)
    #maxBatchSize: 28000000
    workers: 4